### PR TITLE
PET HOTEL: DONE

### PR DESCRIPTION
**Pull request by IsmaelP19**
Added fully support to the Pet Hotel feature and ability to delete a booking

### CODE REVIEW

**Comment by gonmarmar5** [comment]
REVISION : Everything is working as expected, only the label "Pets" when creating a new booking needs to be changed to "Mascotas" in order to traduced all the website to Spanish.

**Review by gonmarmar5 — CHANGES_REQUESTED** [review]
REVISION : Everything is working as expected, only the label "Pets" when creating a new booking needs to be changed to "Mascotas" in order to traduced all the website to Spanish.

**Comment by IsmaelP19** [comment]
> REVISION : Everything is working as expected, only the label "Pets" when creating a new booking needs to be changed to "Mascotas" in order to traduced all the website to Spanish.

Should be fixed by now. Additionally, i fixed the delete method of Booking Controller and now admins have permissions to delete a booking knowing its bookingId via endpoint.

**Review by gonmarmar5 — APPROVED** [review]
Everything is working as expected, well done!

**Pull request merged**
